# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f68a199e607cb94608ddf3c33878479156f58cca15b5de487a7c5736dbbdccfe4ab6610d85de622af6373f057a8f0093f0a14e18f8720fa482d256077eb58f3c

test:
  secret_key_base: b60b13ab1ed42939676ab0cbe65577986ba8164448468568966dcd50decbb6dbdcf395b008bd7425c8ff34a4312afc4e5486499eae20202a61b002085658f19f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
